name: lib-swoole

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ '8.0', '8.1', '8.2', '8.3' ]
    steps:
      - uses: actions/checkout@v4
      - name: install-deps
        run: sudo apt update -y && sudo apt install -y libcurl4-openssl-dev php-curl libc-ares-dev python3 python3-dev
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php }}"
          coverage: none
      - name: Show machine information
        run: |
          date
          env
          uname -a
          ulimit -a
          php -v
          php --ini
          ls -al
          pwd
          echo "`git log -20 --pretty --oneline`"
          echo "`git log -10 --stat --pretty --oneline`"
      - name: Build
        run: |
          phpize
          configure --with-python-config=python3-config
          make -j $(nproc)
          make install

      - name: Run phpunit test
        run: |
          composer install
          composer test
